# Generated by Django 3.1.6 on 2021-05-11 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id_pokemon', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('hp', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('defensa', models.IntegerField()),
                ('ataque_especial', models.IntegerField()),
                ('defensa_especial', models.IntegerField()),
                ('velocidad', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEvolucion',
            fields=[
                ('id_pokemon', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evolucion', models.CharField(choices=[('PreEvolucion', 'PreEvolucion'), ('PostEvolucion', 'PostEvolucion')], max_length=100, null=True)),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemons.pokemon')),
                ('pokemon_evolucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemons.pokemonevolucion')),
            ],
        ),
    ]
