# Generated by Django 3.1.6 on 2021-05-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_auto_20210511_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
